### ISSUE TITLE
NameError: name 'i' is not defined

### ISSUE THREAD

**Issue by YuQianzi** [LJF1113/IPAD#1]
Traceback (most recent call last):
  File "train.py", line 472, in <module>
    Recon_frames = model.forward(net_in)
  File "/home/user/anaconda3/envs/ipad/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/user/anaconda3/envs/ipad/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/user/anaconda3/envs/ipad/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/user/anaconda3/envs/ipad/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
NameError: Caught NameError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/user/anaconda3/envs/ipad/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/user/anaconda3/envs/ipad/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/yuqianzi/IPAD/model/video_swin_transformer.py", line 41, in forward
    res_mem = self.mem_rep(feature, recon_index)
  File "/home/user/anaconda3/envs/ipad/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/yuqianzi/IPAD/model/memory_module.py", line 82, in forward
    y_and = self.memory(x,period_score)
  File "/home/user/anaconda3/envs/ipad/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/yuqianzi/IPAD/model/memory_module.py", line 34, in forward
    a = score[i]
NameError: name 'i' is not defined

**Comment by YuQianzi** [comment]
thank you for your awesome work! I want to ask whether there are any mistakes in the code with this version, as shown above.

**Comment by liuxy1005** [comment]
Have you solved this problem? Can we have a conversation?

**Comment by YuQianzi** [comment]
> Have you solved this problem? Can we have a conversation?

not yet

**Comment by liuxy1005** [comment]
I temporarily set i to 0, and I have been debugged and passed.

**Comment by IceIce1ce** [comment]
Hi @LiuXY3366, how can you solve this problem? We just need to set i to 0. Is it right?

**Comment by YuQianzi** [comment]
You can try this code: https://github.com/YuQianzi/INFP

**Comment by IceIce1ce** [comment]
Hi @YuQianzi, in your repo, I found that the download link of the prepared dataset need a permission to access. Can you check your download link?

**Comment by YuQianzi** [comment]
@IceIce1ce Sorry, it's my first time to upload such file. I've adjusted the download permission, please try again.

**Comment by IceIce1ce** [comment]
I tried it and your code can run well. Thanks for sharing your great work.
